global:
  resolve_timeout: 5m
  title: prometheus
# 自定义 通知的模板的 目录 或者 文件.
#templates:
#  - "/etc/alertmanager/config/dingtalk.tmpl" ##注意：此路径不能更改 
route:
  group_by:
  - alertname
  - cluster
  - service
  group_wait: 10m
  group_interval: 10s  # 当第一个通知发送，等待多久发送压缩的警报
  repeat_interval: 10m #如果报警发送成功, 等待多久重新发送一次
  receiver: dingtalk 
  routes:
  - receiver: dingtalk 
    match_re:
      severity: critical
  - receiver: "null"
    match:
      alertname: Watchdog
receivers:
- name: 'dingtalk'
  email_configs:
  - to: "xxx@xxxxx.com"
    send_resolved: true
    from: "xxx@xxxxx.com"
    smarthost:  "smtp.xxxxx.com:25"
    auth_username: "xxx@xxxxx.com"
    auth_password: "1qwe1234qwe"
  webhook_configs:
  - url: 'http://dingtalk-hook:8060/dingtalk/webhook1/send'
    send_resolved: true  

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    #equal: ['alertname']
    #equal: ['alertname', 'dev', 'instance']
