kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 10.32.3.60:6789,10.32.3.63:6789,10.32.3.65:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: default
  adminSecretName: ceph-admin-secret
  userId: kube
  userSecretNamespace: default
  userSecretName: ceph-secret
  imageFormat: "2"
  imageFeatures: layering
